### ISSUE TITLE
Post Editor for G+

### ISSUE THREAD

**Issue by christysandhoff** [PaulSpoerry/PostEditorForGooglePlus#5]
Post Editor not working for me.  I have uploaded it.  I even restarted Chrome browser.  It shows in my tools, but is not in my stream to use.﻿

**Comment by PaulSpoerry** [comment]
@christysandhoff Can you tell me a little about your setup?  Which version of Chrome, kind of computer, that sort of stuff. Also.. do you use any other Google+ extensions and if so which ones are they?

**Comment by christysandhoff** [comment]
I have an iMac OSX 10.9.2 and I am browsing with Chrome 33.0.1750.152.
Other G+ extensions are attachments.me, EasyVoiceSearch, Gmelius, Google
Cast, GoogleVoice, Talk to Type.
Thanks for helping.

Christy Sandhoff
530-906-5600 voice
888-267-7617 fax

**Comment by PaulSpoerry** [comment]
@christysandhoff I just pushed up a new version and have tested it every way I can think of... can you give it a shot and report back if it works for you now?

**Comment by christysandhoff** [comment]
Dang, still not working.  Let me try and close and reopen Chrome browser as
soon as I am finished with the live stream I am doing.
Will let you know later.

Christy Sandhoff
530-906-5600 voice
888-267-7617 fax

**Comment by PaulSpoerry** [comment]
Dang no way! ok lemme know after you restart. If it's still there I'm gunna have to make a VM when I get some spare time and load up the extensions you have. It's GOT to be something conflicting with it.

**Comment by christysandhoff** [comment]
Still not working.....here are the extensions I have and all are enabled
even though in this email it doesn't show the box checked.  If you want to
do a screen share or hang out later, let me know and we can pick a time
that's good.

Developer mode
 Load unpacked extension... Pack extension...
Update extensions now
 Attachments.me for Gmail, Dropbox, Box, Drive 1.8.6

Easily share and save your attachments. Connects to Dropbox, Google Drive,
SkyDrive, and Box. Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/gdgofjdapkmlgpgjfielacjckplcdjjk
ID: gdgofjdapkmlgpgjfielacjckplcdjjk
Inspect views: background.html chrome://extensions-frame/#
Allow in incognito
Enabled
 Chrome Remote Desktop 34.0.1847.88

Access other computers or allow another user to access your computer
securely over the Internet. Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/gbchcmhmhahfdphkhkmpfmihenigjmpp
ID: gbchcmhmhahfdphkhkmpfmihenigjmpp
Allow in incognito
  Allow access to file URLs
Enabled
 EasyVoiceSearch 1.2

Voice search from anywhere! Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/ifabnpjjgbggngmgijikmfjkppdhfpgj
ID: ifabnpjjgbggngmgijikmfjkppdhfpgj
Inspect views: background page chrome://extensions-frame/#
Allow in incognito
 Options chrome://extensions-frame/#
Enabled
 Facebook AdBlock 1.0.11

Tired of Facebook Ads? with 'Facebook AdBlock', you can block and remove
ads and never see them again! Permissions chrome://extensions-frame/# Visit
website http://www.facebook.com/remove.all.ads
ID: lfpacabphcagfehdgnigmfnbjdampbaa
Inspect views: background page chrome://extensions-frame/#
Allow in incognito
Enabled
 Gmelius 5.7.7.3

Gmail(tm), cleaner, smarter, the way you want it! Gmelius helps you protect
your privacy and boost your email productivity.
Permissionschrome://extensions-frame/#
 Visit website http://gmelius.com/
ID: dheionainndbbpoacpnopgmnihkcmnkl
Inspect views: background page chrome://extensions-frame/#
Allow in incognito
 Options chrome://extensions-frame/#
Enabled
 Google Cast 14.305.0.0

Send content to your Chromecast and other devices that support Google Cast.
Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/boadgeojelhgndaghljhdicfkmllpafd
ID: boadgeojelhgndaghljhdicfkmllpafd
Inspect views: background.html chrome://extensions-frame/#
Allow in incognito
 Options chrome://extensions-frame/#
Enabled
 Google Voice (by Google) 2.4.4

Make calls, send SMS, preview Inbox, and get notified of new messages. (US
only)Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/kcnhkahnjcbndmmehfkdnkjomaanaooo
ID: kcnhkahnjcbndmmehfkdnkjomaanaooo
Inspect views: background.html (Inactive) chrome://extensions-frame/#
Allow in incognito
 Options chrome://extensions-frame/#
Enabled
 Oweb Voice Input 36

Input texts to website's text boxes by speaking.
Permissionschrome://extensions-frame/#
 Visit websitehttps://chrome.google.com/webstore/detail/lffebcpgjecadnkcmdcgklbnphfdjbck
ID: lffebcpgjecadnkcmdcgklbnphfdjbck
Inspect views: background.html chrome://extensions-frame/#
Allow in incognito
 Options chrome://extensions-frame/#
Enabled
 Post Editor for Google+(tm) 1.1.0

Provide simple formatting assistance for Google+.
Permissionschrome://extensions-frame/#
 Visit websitehttp://www.paulspoerry.com/code/post-editor-for-google-plus/
ID: canbakmdapinjpiabkbdgmpenllifmij
Allow in incognito
Enabled
 Talk to Type 1.1

Talk to type. Simple. To type into text box use the mic icon while speaking
and it populates the text box automatically. Have fun
Permissionschrome://extensions-frame/#
 Visit website http://tejji.com/
ID: ioofjgndhocbegkdmlenfhmfbidepgma
Inspect views: background.htm chrome://extensions-frame/#
Allow in incognito
  Allow access to file URLs Options chrome://extensions-frame/#
Enabled
 Voice Search 1.1.3

Search by speaking. Permissions chrome://extensions-frame/# Visit
websitehttps://chrome.google.com/webstore/detail/hhfkcobomkalfdlmkongnhnhahkmnaad
ID: hhfkcobomkalfdlmkongnhnhahkmnaad
Inspect views: views/background.xhtml chrome://extensions-frame/#
Allow in incognito
  Allow access to file URLs Options chrome://extensions-frame/#
Enabled
 Get more extensionshttps://chrome.google.com/webstore/category/extensions?hl=en-USKeyboard
shortcuts chrome://extensions-frame/#

Christy Sandhoff
530-906-5600 voice
888-267-7617 fax

**Comment by klusterr** [comment]
I am also having an issue with the Chrome extension.
Post Editor doesn't appear when I enable it. It also doesn't have a Show/Hide Button functionality on the Tools > Extensions menu. When I disable it and re-enable it the result is the same.

Looking for a solution...

**Comment by PaulSpoerry** [comment]
@klusterr There's a lot happening on the G+ page and a lot of elements are injected after the page appears to have loaded. For instance you'll be able to post but not see the side chat bar for a bit after sometimes. So I would first recommend opening Chrome, going to the G+ homepage (the regular stream) and just wait a minute even after everything looks like it's loaded. Then try to share something and see if it appears. 

I'm unsure what you mean by "how/Hide Button functionality". The extension has no visible toolbar button or anything like that. You'll just see it appear on the page once loaded.

**Comment by Danwilcox82** [comment]
In general, Post Editor works great! Now and again like with the others here it won't load when I go to post on G+ unless I reload the page. However, seeing as though other folks have had the same issues with it it seems to be something that will work itself out in time.

**Comment by PaulSpoerry** [comment]
@Danwilcox82 Glad it works well in general! My code is pretty straight forward... it just polls the page looking for the elements to become available (they're NOT all available when the page looks like it's all loaded.. Google does all kinds of code injection after the page has completed!). When it detects the element it's going to attach to it just starts using JQuery to attach the PostEditor elements. My best guess is that sometimes parts become available and my code fires, and then G+ finishes doing whatever it is it's doing, and in those instances it just doesn't work. As I get time I attempt to recreate other users problems (going so far as to create virtual machines, when it's simple enough to do so, that match their machine/browser configuration) to track down the oddities some people have. It's weird because most everyone it works great for... and the others... it's difficult to track it down. All and all though... glad it's now working for the most part.

**Comment by kimbeasley** [comment]
Love your extension! Installed on Sept 3 and used a couple of times. Then when I tried to create new posts again on Sept 4, Post Editor wasn't an option. Then I checked my About Chrome section to see what version of Chrome I had installed. Noticed that my Chrome wasn't up to date so I updated. Then the Post Editor appeared. Just thought I would share this tip in case anyone else is having an issue too. :)

**Comment by PaulSpoerry** [comment]
Thanks @kimbeasley that's interesting. Do you happen to know what your version was before and after the update?

**Comment by kimbeasley** [comment]
I don't know the before version however here's the after version: 37.0.2062.103
m

  _Kim Beasley,_
- CEO/Social Media Strategist *_Kim Beasley Consulting_
  kim@kimbeasley.com  | http://kimbeasley.com
  [image: Facebook]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/99ee44aa067caffad60bbe71dd08adea?ytl=http%3A%2F%2Fwww.facebook.com%2FKimABeasley
  [image:
  Facebook Page]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/0a9c8c391982a17946953783b8c1a357?ytl=http%3A%2F%2Ffacebook.com%2FSocialMediaToolCoach
  [image:
  Twitter]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/c93b1c8b21fe8347aca0ffb59c3be633?ytl=http%3A%2F%2Ftwitter.com%2Fkimbeasley
  [image:
  LinkedIn]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/dca13985c29be7ea0b004324926c05ca?ytl=http%3A%2F%2Flinkedin.com%2Fin%2Fkbeasley%2F
  [image:
  Google Plus]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/81a802249c27ebe3ddeda186d63745eb?ytl=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BKimBeasley%2Fposts
  [image:
  Google Plus Page]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/9b0f1111476dc0e98d19d18169be670d?ytl=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F113404037141063682408
  [image:
  pinterest]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/5eded7068913a48dea52e43fd9c9cb1b?ytl=http%3A%2F%2Fpinterest.com%2Fkimabeasley
  [image:
  YouTube]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/d0ca1cb068bbea8f18e9562b59764ee2?ytl=http%3A%2F%2Fwww.youtube.com%2Fuser%2FSocialMediaToolCoach
  [image: undefined]
  https://t.yesware.com/tl/9779b022640f8169b59dd3c270247e838687cad9/e7f305b8166d0130d2e24daec359b6e1/d2ea1c0b3a9c0d927f949c4757baecdb?ytl=https%3A%2F%2Fwww.facebook.com%2FSocialMediaToolCoach

**Comment by PaulSpoerry** [comment]
Thanks.
